name: escucha_tu_historia
description: "Aplicación para escuchar historias del pueblo de Martos."
version: 1.0.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^6.0.0
  carousel_slider: ^4.2.1
  country_flags: ^2.2.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.6
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  go_router: ^14.1.4
  http: ^1.2.1
  package_info_plus: ^8.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  icon_size: 192 # min:48, max:192, default: 48
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_intl:
  enabled: true
